# 自作のweight matrixだと変数が吸収される場合がある

自作のweight matrixで単項式順序を決める場合以下の点に注意
・

In [4]:
import numpy as np
np.__version__

'1.26.4'

In [2]:
%pwd
%pip install --upgrade scipy
%pip install numpy==1.26.4
%pip install pulp

import numpy as np

load("/app/src/lib/sampler.sage")
load("/app/src/lib/buchberger.sage")
load("/app/src/lib/utils.sage")
load("/app/src/lib/differential_evolution.sage")

Note: you may need to restart the kernel to use updated packages.
Note: you may need to restart the kernel to use updated packages.
Note: you may need to restart the kernel to use updated packages.


In [71]:
params = np.array([3.1, 2.4, 1.7, 0.9, 0.5, -1.1, 0.3, -6.7, 3.2])
# フルランクかどうかの判定
variables = 3
int_matrix = np.array(list(map(int, params))).reshape(variables, variables)
rank = np.linalg.matrix_rank(int_matrix)
print(int_matrix)
print(rank)


[[ 3  2  1]
 [ 0  0 -1]
 [ 0 -6  3]]
3


In [111]:
import numpy as np
# M = np.random.randn(3,3) # 後で修正　一様な確率で値を取る
M = np.random.uniform(-1, 1, (3, 3))

T = TermOrder(matrix(M.tolist()))
print(M)
print('rank', np.linalg.matrix_rank(M, tol=0.1))

# # s = np.linalg.svdvals(M)
# print(s[0]/s[-1])

P = PolynomialRing(QQ, 3, 'x', order=T)
x0, x1, x2 = P.gens()

f = x0 + x1 + x2
print(f'now  {f}')
print(np.sum(M, axis=1))
print(np.argmax(np.sum(M, axis=1)))
print(f'x0, x1, x2: {x0+0, x1+0, x2+0}')
print(f'x0, x1, x2: {P(x0+1), P(x1+1),P(x2+1)}')

M_int = M.astype(int)
print(M_int)
print('validation:', validation(M_int))

x0 > x1

[[ 0.23670016  0.41960864  0.77861938]
 [-0.86078706 -0.26111843 -0.60990079]
 [-0.08692064  0.55729737  0.24005217]]
rank 3
now  3*x0
[ 1.43492818 -1.73180627  0.7104289 ]
0
x0, x1, x2: (x0, x1, x2)
x0, x1, x2: (2*x0, 2*x1, 2*x2)
[[0 0 0]
 [0 0 0]
 [0 0 0]]
validation: False


False

In [120]:
P.term_order().matrix()

[ -0.203728856889124  1.0924125732623968  0.7379993531613699]
[ 1.8199822140671946 0.34312381419093807  0.4638214898109969]
[ 1.2226876686369712 0.16672179475548043   1.061517104639763]

In [79]:
vars(T)

{'_blocks': (),
 '_weights': (1.922909501601129, 1.526552888388681, 0.23848089221453517),
 '_matrix': [  1.922909501601129   1.526552888388681 0.23848089221453517]
 [ 0.4296442401699777 0.20367747421771087  2.9787591582465396]
 [  1.606434390697848  1.0535169621570302  1.3026206165787158],
 '_singular_moreblocks': 0,
 '_singular_ringorder_column': None,
 '_length': 3,
 '_name': 'matrix',
 '_singular_str': 'M(1,1,0,0,0,2,1,1,1)',
 '_macaulay2_str': '',
 '_magma_str': '"weight",[1,1,0,0,0,2,1,1,1]',
 '__doc__': '\nMatrix term order defined by a matrix A.\n\n`x^a < x^b` if and only if `x^{Aa} < x^{Ab}` where `<` is the lexicographic term order.\n'}

In [ ]:
Mat = np.array([0,0,1,-1,0,0,0,0,3])
Mat = Mat.reshape(3,3)
np.linalg.matrix_rank(Mat, tol=0.001)

In [ ]:
print(M)
np.sum(M[:,1:], axis=1)

In [ ]:
print(vars(T))
print(T)
print(f)

In [ ]:
vars(TermOrder('lex'))

In [ ]:
# P = PolynomialRing(QQ, variables, 'x', order=TermOrder(matrix_))
# x0, x1, x2 = P.gens()

m_lex = matrix([[1,0,0], [0,1,0], [0,0,1]])
T1 = TermOrder(m_lex)

matrix = randint(0, 1, (3, 3))
print(matrix)

# T = TermOrder(matrix([[1,1.5,1], [1,0.3,-1], [1,-1,1]]))

# P = PolynomialRing(QQ, 3, 'x', order=T)
# x0, x1, x2 = P.gens()
# polynomial_list = [-17/6*x0^2*x1*x2 + 17/13*x0*x2 + 17/14*x1^4*x2^5, 9/10*x0*x1*x2 + 3/10*x1^2 - 8/15*x1*x2^2 + 5/9*x1]
# print(f'now  {polynomial_list}')

In [ ]:
# A = np.array([[1, 1, 4, 0, 1],
#               [0, 3, 1, 3, 2],
#               [1, 3, 0, 0, 1],
#               [2, 4, 3, 1, 1]]) # Aを定義する。

# np.linalg.matrix_rank(A) # Aのランクを計算する。
# type(A)

In [ ]:
m_grevlex = matrix([[1,1,1], 
                    [0,0,-1], 
                    [0,-1,0]])


T3 = TermOrder(m_grevlex)
P_grevlex = PolynomialRing(QQ, 3, 'x', order=T3)
x0, x1, x2 = P_grevlex.gens()
polynomial_list = [-17/6*x0^2*x1*x2 + 17/13*x0*x2 + 17/14*x1^4*x2^5, 9/10*x0*x1*x2 + 3/10*x1^2 - 8/15*x1*x2^2 + 5/9*x1]
buchberger(P_grevlex, polynomial_list)