# lex順序内で変数順序を変えて実験

In [2]:
load("/app/src/lib/sampler.sage")
load("/app/src/lib/buchberger.sage")
load("/app/src/lib/utils.sage")

In [4]:
import numpy as np
import itertools

np.__version__

'2.1.1'

In [4]:
P_grevlex = PolynomialRing(QQ, 3, 'x', order='degrevlex')

In [24]:
conditions = {  'max_degree'      : 10, 
                'min_degree'      : 2,
                'max_num_terms'   : 3, 
                'max_coeff'       : 20,
                'num_bound'       : 10,
                'nonzero_instance': True,}

psampler = Polynomial_Sampler(P_grevlex, 
                            degree_sampling='uniform', 
                            term_sampling='uniform', 
                            strictly_conditioned=True, 
                            conditions=conditions)

set_random_seed(1)
F = psampler.sample(num_samples=2)
F

[10*x0^3*x1^5 - 1/2*x0^2*x2^5, 2/3*x0^7*x2^2 - 2*x1*x2^7]

In [33]:
# 3つのリスト
lists = [[1, 0, 0], [0, 1, 0], [0, 0, 1]]

# リストのすべての順列を取得し、それぞれを連結する
all_combinations = [sum(p, []) for p in itertools.permutations(lists)]

# 結果を表示
result = []
for combination in all_combinations:
    additions, GB = output_additions(combination, F, 3, True)
    result.append((np.array(combination).reshape(3,3), additions))
    
result

[(array([[1, 0, 0],
         [0, 1, 0],
         [0, 0, 1]]),
  21),
 (array([[1, 0, 0],
         [0, 0, 1],
         [0, 1, 0]]),
  21),
 (array([[0, 1, 0],
         [1, 0, 0],
         [0, 0, 1]]),
  15),
 (array([[0, 1, 0],
         [0, 0, 1],
         [1, 0, 0]]),
  15),
 (array([[0, 0, 1],
         [1, 0, 0],
         [0, 1, 0]]),
  4),
 (array([[0, 0, 1],
         [0, 1, 0],
         [1, 0, 0]]),
  4)]

In [34]:
variables = 3
matrix_ = matrix(3, all_combinations[0])
print(matrix_)

P = PolynomialRing(QQ, variables, 'x', order=TermOrder(matrix_))
# P = PolynomialRing(QQ, variables, 'x', order='degrevlex')
# cal_groebner_basis(P, F)

buchberger(P, F, )

[1 0 0]
[0 1 0]
[0 0 1]


([x1^37*x2^7 - 1/3840000000*x1*x2^37,
  x0*x1*x2^32 - 192000000*x1^32*x2^7,
  x0*x1^6*x2^7 - 1/20*x1*x2^12,
  x0^2*x2^27 - 9600000*x1^26*x2^7,
  x0^3*x2^22 - 480000*x1^21*x2^7,
  x0^3*x1^5 - 1/20*x0^2*x2^5,
  x0^4*x2^17 - 24000*x1^16*x2^7,
  x0^5*x2^12 - 1200*x1^11*x2^7,
  x0^6*x2^7 - 60*x1^6*x2^7,
  x0^7*x2^2 - 3*x1*x2^7],
 {'zero_reductions': 7,
  'nonzero_reductions': 8,
  'polynomial_additions': 21,
  'total_reward': -21.0000000000000,
  'discounted_return': -19.4784981491940})

In [2]:
np.__version__

NameError: name 'np' is not defined